### ISSUE TITLE
Follow symlinks when checking exclusion/inclusion paths in stdio adapter

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#179]
# Crash Reproducer

`LD_PRELOAD` the stdio adapter with a basic program (e.g., hello world) with `HERMES_CONF` set to a location involving a symlink.

# Explanation

On Ares, `/home` is a symlink to `/mnt/common`. When `PopulateBufferingPath` adds the hermes conf file to `hermes_paths_exclusion` it adds the `/home` version without expanding the symlink. Then on `fclose`, `IsTracked` returns `true` because when the `FILE*` is converted to a path in `GetFilenameFromFP` it calls `readlink` which looks for the expanded symlink target in the exclusion list, which it doesn't find.

**Comment by gheber** [comment]
Please create a to-the-point error message and revisit post beta.
