### ISSUE TITLE
LocalReadBufferById heap-buffer-overflow

### ISSUE THREAD

**Issue by jya-kmu** [HDFGroup/hermes#200]
To reproduce the issue in `hermes::LocalReadBufferById`

1. Clone [Hermes](https://github.com/HDFGroup/hermes.git) and checkout kimmy/c_wrapper branch and install
2. Clone [hdf5](https://github.com/jya-kmu/hdf5.git) and checkout hermes_vfd branch and install
3. Clone [hdf5-iotest](https://github.com/jya-kmu/hdf5-iotest.git) and checkout hermes-vfd branch
4. export HERMES_CONF=path_to_hermes-conf-file (provided in hdf5-iotest dir)
5. In file `src/hdf5_iotest.ini`, modify `steps = 20` to `steps = 3` @line 3 and modify `posix` to `hermes` for `single-process` @line 18
6. Run `GLOG_minloglevel=2 ./src/hdf5_iotest ../src/hdf5_iotest.ini`, and after four sections it should generate the error
heap-buffer-overflow in `LocalReadBufferById`.

**Comment by ChristopherHogan** [comment]
Can you post the stack trace you showed me before?

**Comment by jya-kmu** [comment]
Good for now. Maybe solved in a different bug.
