### ISSUE TITLE
Move Hermes wiki to Github

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#215]
The quick and dirty migration is done. Still TODO:
* Move all images from the wiki server to GH.
* Go over all pages and check for errors.
* Make sure all links work.
* Add a table of contents
* Figure out something for displaying latex.

**Comment by gheber** [comment]
This might work for equations https://i.upmath.me/g/

**Comment by gheber** [comment]
Done. I have MediaWiki snapshots, and PDFs of the old pages can be found in `images/hermes.page` of https://github.com/HDFGroup/hermes.wiki.git
