### ISSUE TITLE
Github Actions failed at Build and Install Dependencies

### ISSUE THREAD

**Issue by jya-kmu** [HDFGroup/hermes#274]
failed at Build and Install Dependencies [failure](https://github.com/HDFGroup/hermes/runs/4094607493?check_suite_focus=true)

Get over the issue with spack v0.16.3, but tests can run for [6 hours](https://github.com/HDFGroup/hermes/actions/runs/1417651715)

**Comment by ChristopherHogan** [comment]
I don't think the tests that ran for 6 hours have anything to do with pinning spack `v0.16.3`. If you look at the output log of those tests, you'll see that the GLOG logging doesn't show up in stdout for the adapter tests, which means it's going to a file somewhere. Doing tons and tons of disk IO in a Github action is likely what caused all those tests to time out.
