### ISSUE TITLE
Provide easier way to add to the adapter exclusion path

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#289]
If you want to exclude a Hermes adapter from intercepting certain paths, you must currently add the directory to `hermes::adapter::kPathExclusions` and recompile. We should allow adding to this list via environment variable or config variable.

**Comment by lukemartinlogan** [comment]
A certain set of paths are provided globally. You can extend the included/excluded paths. Included paths are checked before excluded ones.
