### ISSUE TITLE
Develop a check list for releases

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hermes#292]
Keep it [in the Wiki](https://github.com/HDFGroup/hermes/wiki/Check-Lists) 

In the future, let's add labels to PRs so that the release tags get populated automatically!

**Comment by ChristopherHogan** [comment]
> In the future, let's add labels to PRs so that the release tags get populated automatically!

#294 enables this.

**Comment by ChristopherHogan** [comment]
The final checklist is [here](https://github.com/HDFGroup/hermes/wiki/Check-Lists#release).
