### ISSUE TITLE
Formatting error in Wiki document

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#325]
I think bold formatting (*) is not right in the following sentence:

```
Given individual or batches of I/O operations (writes and reads), the main challenge for such a buffering system is to determine where in DDSH a given data item is *best/well/optimally-*placed at that point in time.
```

[1] https://github.com/HDFGroup/hermes/wiki

**Comment by ChristopherHogan** [comment]
Fixed. Thanks.  @hyoklee, I gave you write access to the repository so feel free to update the wiki if you see more mistakes.
