### ISSUE TITLE
Sync version in docs (Doxygen).

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#346]
https://docs.hdfgroup.org/hermes/ says 1.0.0-beta while release is 0.3.0-beta.

How can we automate docs publication?
I don't see pub/sub APIs in docs.

**Comment by ChristopherHogan** [comment]
There is an existing issue for automating doxygen builds and uploading them to S3: #280

**Comment by hyoklee** [comment]
I wish we could host one under gh-pages branch. (e.g., https://hyoklee.github.io/hermes/html/)
It can be automatically generated with Actions.

**Comment by ChristopherHogan** [comment]
I seem to recall that Anthony had a problem with using github pages because he wants the docs to be on a site with a specific "hermes" URL instead of an HDFGroup one. We can ask him about it during the next meeting. Using github pages would simplify things.
