### ISSUE TITLE
Preserve "width" of numbers appended to host names in config parser

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#375]
`config_parser.cc:ParseRangeList` currently doesn't preserve the width of host numbers. For example, to specify the server list

```
host-001
host-002
host-003
```
in the config file, one would set `rpc_server_base_name = "host-"` and `rpc_host_number_range = {001-003};`. However, that would result in the following incorrect list of hostnames:

```
host-1
host-2
host-3
```

We need to save the width and format the numbers appropriately with leading fill `0`s when constructing the host names.

**Comment by ChristopherHogan** [comment]
The `rpc_server_host_file` config parameter can serve as a workaround until this is fixed.

**Comment by lukemartinlogan** [comment]
Fixed by creating a hostname parser.
