### ISSUE TITLE
The VFD doesn't work with HDF5 apps in C

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#385]
There are some incompatibilities with how HDF5, the VFD, and GLOG interact. The HDF5 library terminates the Hermes VFD in a function registered with `atexit`. So the flow is like this:

```C
int main() {
  // My HDF5 app
  return 0; 
  // Hermes is shutdown here
}
```
The problem is that static variables in GLOG are destroyed after `return 0` but before Hermes shuts down. Then Hermes tries to use GLOG during shutdown, and it crashes. Static variable destruction and `atexit` functions are run in the reverse order in which they were initialized/called. Currently the flow looks like this:

1. The HDF5 library registers `H5FD__hermes_term` with `atexit`
2. Hermes is initialized, which initializes GLOG

Destruction happens in reverse order, so GLOG static objects are destroyed, then `H5FD__hermes_term` runs. The strange thing is that this only happens when the application is compiled as a C program. If I compile as C++, it works, although I think static variable initialization/destruction order can be randomized, so it may not always work.

To get the correct behavior we need to initialize Hermes before HDF5 registers `H5FD__hermes_term`. I tested this theory by calling `dlopen("libhermes.so")` at the top of the `main` function in `ior`. It worked, which confirms the theory, but I don't see a way to make that happen for arbitrary apps. We need a VFD hook that runs before `atexit` is called, which happens when HDF5 initializes.

**Comment by ChristopherHogan** [comment]
We would have to either find a replacement logging library or write our own. Also, there's no guarantee a replacement library wouldn't use a static object in a similar way, so we'd still have the same issue. I definitely favor simplifying the dependencies though, if possible.

**Comment by hyoklee** [comment]
I am wondering why generic Linux logging (e.g., syslog()) / error routines (e.g., perror()) were not used Hermes.

**Comment by ChristopherHogan** [comment]
I can't speak for Gerd (he was the one who made the decision), but I assume it was because GLOG offers a C++ API. In addition, one feature of GLOG which I use all the time is the ability to control the log level at runtime via environment variables. I could be wrong, but looking at the syslog documentation I don't see that capability. GLOG even lets you change the logging verbosity at runtime of individual files.

**Comment by hyoklee** [comment]
Thanks. I was curious what GLOG is useful for.

**Comment by ChristopherHogan** [comment]
Another temporary workaround is to set the environment variable `GLOG_minloglevel=2`. This will skip log messages less severe than `ERROR`, and avoid the code paths that cause the reading of a deleted object.
