### ISSUE TITLE
[Q] When to use  #include "glog/logging.h" instead of #include <glog/logging.h>?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#408]
https://github.com/HDFGroup/hermes/search?p=2&q=glog gives inconsistencies in Hermes code.

In general, when (not) to use "glog/logging.h" for (adapter) developers?

**Comment by ChristopherHogan** [comment]
I try to follow the convention that `<>` is for third party dependencies and `""` is for headers belonging to the project. That means it should be `<glog/logging.h>`.
