### ISSUE TITLE
RandomPlacement always fails

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#41]
`RandomPlacement` will never return a placement schema, but instead will always return a failure `Status`. After some investigating, it appears as if the duplicated code in `data_placement_engine.cc:RandomPlacement` and `dpe_test_random_placement.cc:RandomPlacement` has diverged. One immediately apparent problem is that `ordered_cap` is not initialized in `data_placement_engine.cc` as it is in `dpe_random_test.cc`. @jya-kmu, could you please refactor the duplication in these two files into shared functions and make sure `RandomPlacement` works properly in both versions? Thanks!

**Comment by jya-kmu** [comment]
I see the issue. I can fix it by initializing `ordered_cap` in `CalculatePlacement` and pass the reference to `RandomPlacement`. Could you elaborate on the "shared functions" approach?

**Comment by ChristopherHogan** [comment]
> Could you elaborate on the "shared functions" approach?

I just mean eliminate the code duplication so we don't have another situation where the two duplicated sections of code diverge like they did here. Pulling out a helper function that both outer functions share is one way to do that.

**Comment by jya-kmu** [comment]
OK. But if you need a quick fix and then do the test, it can be fixed quickly. Since I need to update all the three schemes, it may take some time.

**Comment by jya-kmu** [comment]
All right.

**Comment by jya-kmu** [comment]
Solved.
