### ISSUE TITLE
Check if NULL pointer is returned before calling fs::exists(hermes_config) in adapter/interceptor.cc.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#438]
The `hermes_config` can be NULL when `HERMES_CONF` is not set.
The following code causes segmentaiton fault when `hermes_config` is NULL.
```
void PopulateBufferingPath() {
  char* hermes_config = getenv(kHermesConf);

  if (fs::exists(hermes_config)) {
    std::string hermes_conf_abs_path =
      WeaklyCanonical(fs::path(hermes_config)).string();

```

**Comment by lukemartinlogan** [comment]
I fixed this issue by creating a centralized hermes::InitConfig function, which checks if this value is null.
