### ISSUE TITLE
GLPK DPE doesn't respect available buffering space

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#439]
To reproduce, uncomment `gcc_hermes(hermes_stdio_low_buf_adapter_test "" "" hermes_small async)` in `adapter/test/stdio/CMakeLists.txt` and run that test via `ctest`. When I stepped through `MinimizeIoTimePlacement` I witnessed the DPE giving out over 1 MiB of buffers in the RAM tier, even though the RAM tier only has ~756 KiB available.

**Comment by hyoklee** [comment]
Chris is not sure whether this was caused by GLPK or pre-existed with OR-Tools.

**Comment by ChristopherHogan** [comment]
`node_state` holds the available capacity in bytes of each candidate `Target` considered for data placement. I guess we need an extra constraint that says no capacity is allowed to go below 0.
