### ISSUE TITLE
Unit tests for UNIX stage-in and stage-out

### ISSUE THREAD

**Issue by lukemartinlogan** [HDFGroup/hermes#451]
The current version of stage-in / stage-out parallelizes I/O by giving each MPI rank a (roughly) equivalent slice of a file to read. This approach isn't perfect, especially for small files. This code really assumes that large files are being staged-in/out, which is the main use case anyway.

However, knowing this, we need to create the following tests:
- [ ] Stage-in and stage-out a UNIX file, where each process gets an equal slice of the file. This test technically exists under data_stager/test/unix/hermes_staging_unix_test.cc. The test doesn't use google test, but it should.
- [ ] Stage-in and stage-out a UNIX file, where the file size is not divisible by the number process ranks. Same as the above case, just with a different file size being created.
- [ ] Stage-in a directory of files.

To complete this task, do the following
1. Convert the unit test in data_stager/test/unix/hermes_staging_unix_test.cc to use google test, instead of my custom format. 
2. Complete the other 2 tests. You should be able to use most of the code in hermes_staging_unix_test.cc for these as well.
3. Create a ctest for each of these tests, instead of my manual work.

**Comment by hyoklee** [comment]
Due to ANL project, I'm assigning it to Luke.
Please rename unix to posix for path name.
