### ISSUE TITLE
Assertion failure occurs in Argobots. 

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#484]
`end_to_end` test fails with assertion failure.

```
global.c:335: finailze_library: 
Assertion `p_global->p_xstream_head == ((void *)0)' failed.
```

The following `delete` code in [rpc_thallium.cc](https://github.com/HDFGroup/hermes/blob/master/src/rpc_thallium.cc) triggered it.

```
/** shut down RPC clients */
void ShutdownRpcClients(RpcContext *rpc) {
  ClientThalliumState *state = GetClientThalliumState(rpc);
  if (state) {
    if (state->engine) {
        delete state->engine;  // This triggers assertion failure.                                                
      state->engine = 0;
    }
    free(state);
    state = 0;
  }
}
```

This happens on Ubuntu-22.04 + gcc-11. 
I tried both the release and latest version of Argobots.
Both failed.

**Comment by lukemartinlogan** [comment]
I stored thallium state in a std::unique_ptr, which was causing data to be released twice. Fixed.
