### ISSUE TITLE
GitHub Actions require re-running in order to be successful

### ISSUE THREAD

**Issue by lukemartinlogan** [HDFGroup/hermes#488]
For some reason, github actions will fail within 5 minutes due to not being able to find pkg-config. Something is buggy with the github action cache. It's strange, but it makes actions take much longer to run as it has to completely re-install all dependencies for each push and commit.

**Comment by hyoklee** [comment]
@lukemartinlogan, I updated the [Developer's Guide](https://github.com/HDFGroup/hermes/wiki/Developer's-Guide#pr-check-failure).
See also PR #504.

**Comment by lukemartinlogan** [comment]
The CI now installs spack packages separate from building Hermes. This results in more consistent and correct caching of packages.
