### ISSUE TITLE
Spack fetches wrong package

### ISSUE THREAD

**Issue by nrj5k** [HDFGroup/hermes#491]
On doing `spack install hermes` it tries to install v0.8.0 but fetches v0.7.0 and fails the subsequent checksum.

I am using Slackware-15.0

```
==> Installing hermes-0.8.0-beta-nczawtda6dvn652zvdz3wlc64cmdjp5w
==> No binary for hermes-0.8.0-beta-nczawtda6dvn652zvdz3wlc64cmdjp5w found: installing from source
==> Fetching https://github.com/HDFGroup/hermes/archive/v0.7.0-beta.tar.gz
==> Error: ChecksumError: sha256 checksum failed for /tmp/user/spack-stage/spack-stage-hermes-0.8.0-beta-nczawtda6dvn652zvdz3wlc64cmdjp5w/v0.7.0-beta.tar.gz
    Expected 697c8b0ca2d94512326d1dc8d1895d3d37fbff708013d7bf578a3158b06cb158 but got 1046f537558e479c8a828fe8e289da410a0f82bdba199a40ea7ff0eb842d9382

/home/user/spack/lib/spack/spack/package_base.py:1460, in do_fetch:
       1457        self.stage.fetch(mirror_only, err_msg=err_msg)
       1458        self._fetch_time = time.time() - start_time
       1459
  >>   1460        if checksum and self.version in self.versions:
       1461            self.stage.check()
       1462
       1463        self.stage.cache_local()
```

**Comment by hyoklee** [comment]
Hi, @nrj5k !

Thank you for your report.

Spack doesn't support v0.8.0 any more. Please update your Spack to use 0.9.0:

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hermes/package.py

We don't recommend 0.8.0.

**Comment by nrj5k** [comment]
But then shouldn't the `spack install hermes` command fetch and install v0.9.0 on its own?

**Comment by hyoklee** [comment]
Please check if you cleared Spack cache.

If you run everything from scratch like Github Action, I can see Spack pulling the right version:

https://github.com/hyoklee/actions/actions/runs/4218016262/jobs/7322212571
