### ISSUE TITLE
Update spack to include jarvis-util as a dependency

### ISSUE THREAD

**Issue by lukemartinlogan** [HDFGroup/hermes#518]
We need to update spack to install ci/jarvis-util automatically. 

Jarvis-util is also being maintained at the following github link: https://github.com/lukemartinlogan/jarvis-util

**Comment by hyoklee** [comment]
@lukemartinlogan , would you please make https://github.com/scs-lab/jarvis-util public?

**Comment by lukemartinlogan** [comment]
It is available now.

**Comment by hyoklee** [comment]
https://github.com/spack/spack/pull/37729
