### ISSUE TITLE
Add a FlushRuntime task

### ISSUE THREAD

**Issue by lukemartinlogan** [HDFGroup/hermes#588]
Right now the code to exit from the runtime doesn't wait for all pending requests to complete. I simply have been waiting until the program terminates. 

FlushRuntime:
1. FlushRuntime task will be replicated across the entire domain. Barrier until short-running requests have completed. 
3. Workers store a count of the amount of work done, excluding long-running tasks and the FlushRuntime task
4. The FlushRuntime task waits until all worker counts are 0
5. FlushRuntime completes

**Comment by hyoklee** [comment]
How to prevent deadlock on step 3?

**Comment by lukemartinlogan** [comment]
I'll explain more formally:

There are three important task types in this scenario:
1. One-off tasks: tasks which will perform some logic and return automatically. For example, creating a bucket in Hermes.
2. Long-running tasks: tasks which run until they are explicitly stopped by a user. For example, Hermes monitoring tasks that periodically update tier capacities.
3. Flush tasks: a task which is waiting for the worker count to become zero

Tasks have a 32-bit flag field. Currently, we have TASK_LONG_RUNNING (1 << 11). If this flag is set to 0, then it's a one-off task. We will need to create a new flag called TASK_FLUSH which will be used to indicate the task is a flushing task and should be ignored by the worker counter.

On each iteration of the worker, we will count the total number of tasks which do not set TASK_LONG_RUNNING and TASK_FLUSH. In other words, we will be counting only one-off tasks that are not the flush task. Since one-off tasks eventually complete on their own, the worker count will become 0 eventually.
