### ISSUE TITLE
Initialize GLOG properly

### ISSUE THREAD

**Issue by ChristopherHogan** [HDFGroup/hermes#98]
Created from JIRA [HERM-55](https://jira.hdfgroup.org/browse/HERM-55)

We currently use it uninitialized so output goes to stdout.

**Comment by gheber** [comment]
**Ensure** that error logging is properly configured out-of-the-box (see #98)
FLAGS_log_dir = "PATH_TO_LOG";   (by user or getcwd)                                                       
FLAGS_v = 2;                                                                                      
google::InitGoogleLogging(argv[0]);

Have them in function `InitHermes`?
